apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-virtual-service
spec:
  hosts:
    - "dev.${CERA_REGION}.circleci-demo-c1.com"
  gateways:
    - istio-ingress/${CERA_REGION}-istio-gateway-2