# Application Name and Version - not required. If not used the Component will not be associated to an Application
Application = "GLOBAL.eddiewebb.CircleCI Orb.CCI Bank Corp"
Application_Version = "1" 

# Define Component Name, Variant and Version - required
Name = "GLOBAL.eddiewebb.CircleCI Orb.Contacts Service"
Variant = "${CIRCLE_BRANCH}"
Version = "${SKAFFOLD_IMAGE_TAG}"

# Key/Values to associate to the Component Version (set by ortelius.bash, which is called by skaffold for components.)
[Attributes]
    DockerBuildDate = "${BLDDATE}"
    DockerRepo = "${DOCKERREPO}"
    DockerSha = "${DOCKERSHA}"
    DockerTag = "${SKAFFOLD_IMAGE_TAG}"
    #SlackChannel = "your Slack Channel" 
    ServiceOwner = "${DHUSER}"
    ServiceOwnerEmail = "eddie@circleci.com"
