version: 2.1

executors:
  base:
    docker:
      - image: cimg/deploy:2022.07
  jdk17:
    docker:
      - image: cimg/openjdk:17.0.3
  python38:
    docker:
      - image: cimg/python:3.8


jobs:
  python-checkstyle:
    executor: python38
    steps:
      - checkout
      - run: pip install pylint
      - run:
          name: Lint Python
          command: pylint --rcfile=./.pylintrc ./src/*/*.py

  python-test:
    executor: python38
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Test Python Services
          command: |
            for SERVICE in "contacts" "userservice"; do
              echo "testing $SERVICE..."
              # save current working dir to memory and cd to src/$SERVICE
              pushd src/$SERVICE
                python3 -m venv $HOME/venv-$SERVICE
                source $HOME/venv-$SERVICE/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                python -m pytest --junit-xml=../../test-reports/report-${SERVICE}.xml -v -p no:warnings
                deactivate
              # return to previously saved path
              popd
            done
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  java-checkstyle:
    executor: jdk17
    steps:
      - checkout
      - run: |
          ./mvnw checkstyle:check

  java-test-and-code-cov:
      executor: jdk17
      steps:
        - checkout
        - run: mkdir test-reports
        - run: |
            ./mvnw test
            for SERVICE in "balancereader" "ledgerwriter" "transactionhistory"; do
            echo "checking $SERVICE..."
            # save current working dir to memory and cd to src/$SERVICE
            pushd src/$SERVICE
            ../../mvnw jacoco:report
            echo "Coverage for $SERVICE:"
            awk -F, \
            '{ instructions += $4 + $5; covered += $5 } END \
            { print covered, "/", instructions, " instructions covered"; \
            print int(100*covered/instructions), "% covered" }' \
            target/site/jacoco/jacoco.csv
            cp target/surefire-reports/*.xml ../../test-reports
            # return to previously saved path
            popd
            done
        - store_test_results:
            path: test-reports
        - store_artifacts:
            path: test-reports

  deploy:
    executor: base
    parameters:
      environment:
        type: string
        default: dev
        description: Environment suffix used by namesapce and SA account name.
    environment:
      K8_USER: boa-pipeline-<<parameters.environment>>
      K8_URL: "https://82BD0213010A79DBD7EAF886E3E553E0.gr7.us-west-2.eks.amazonaws.com"
      K8_CLUSTER: cera-solutions-eng
    steps:
      - checkout
      - run: echo "Now using namespace ${K8_NAMESPACE}"
      - use_service_account
      - run: |
          sudo apt update && sudo apt install kubectl -y
          kubectl config view
          kubectl get serviceaccounts -n ${K8_NAMESPACE}
      - run: 
          name: Deploy BoA
          command: |
            kubectl apply -f ./extras/jwt/jwt-secret.yaml -n ${K8_NAMESPACE}
            kubectl apply -f ./kubernetes-manifests -n ${K8_NAMESPACE}
      - run:
          name: Wait for deployment
          command: |
            kubectl wait deployment -n ${K8_NAMESPACE} frontend --for condition=Available=True --timeout=90s
      - run: 
          name: Print Frontend URL
          command: kubectl get service frontend -n ${K8_NAMESPACE} | awk '{print $4}'

workflows:
  main:
    jobs:
      - java-checkstyle
      - java-test-and-code-cov
      - python-checkstyle
      - python-test
      - deploy:
          name: Deploy Dev
          environment: dev
          requires: [ python-test, java-test-and-code-cov ]
          context: [ cera-boa-dev ]
      - deploy:
          name: Deploy Production
          requires: [ Deploy Dev ]
          context: [ cera-boa-prod ]
          environment: prod
          filters:
            branches:
              only: [ main ]


commands:
  use_service_account:
  # This command uses the assigned context to hydrate a kubeconfig from the given service account.
  # These values are automatically injected into the 2 app contexts by the `reference-architecture` project
    steps:
      - run:
          command: |
            echo ${K8_CERT} | base64 -d > ca.crt
            kubectl config set-cluster ${K8_CLUSTER} --server=${K8_URL} --certificate-authority=ca.crt
            export DECODED_TOKEN=$(echo ${K8_TOKEN} | base64 -d) #kubectl prints an encoded value, MUST decode it to work.
            kubectl config set-credentials ${K8_USER} --token=${DECODED_TOKEN}
            kubectl config set-context default --user=${K8_USER}  --cluster=${K8_CLUSTER} --namespace ${K8_NAMESPACE}
            kubectl config use-context default
          name: Use K8s token & cert to create kubeconfig.